#cloud:
#  gateway:
#    routes:
#    - id: userService
#       uri : lb://userService
#       predicates: 
#       - path=/user/**
#       
#    - id: contactService
#       uri : lb://contactService
#       predicates: 
#       - path=/contact/**   